### ISSUE TITLE
Another language

### ISSUE THREAD

**Issue by jeffersonw2020** [tksh164/change-windows-language-regional-settings#1]
Hi,
How do I obtain these data to install another language?

OffsetToCabFileInIsoFile = 0x107d35800L
CabFileSize = 54130307
CabFileHash = '298667B848087EA1377F483DC15597FD5F38A492'

**Comment by tksh164** [comment]
Hi @jeffersonw2020, thank you for reaching out to me.

Each data meaning the following:

- **OffsetToCabFileInIsoFile** - The offset in bytes from the head of the language pack ISO file.
- **CabFileSize** - The cab file size of the language that you want.
- **CabFileHash** - The file hash of the cab file by SHA1.

The steps of obtaining each data are as follows.

1. Download the language pack ISO file. The following are examples.

    - Windows Server 2022 - https://software-static.download.prss.microsoft.com/pr/download/20348.1.210507-1500.fe_release_amd64fre_SERVER_LOF_PACKAGES_OEM.iso
    - Windows Server 2019 - https://software-static.download.prss.microsoft.com/pr/download/17763.1.180914-1434.rs5_release_SERVERLANGPACKDVD_OEM_MULTI.iso

2. Mount the download language pack ISO file. You can do it like the following if do it by PowerShell.

    ```powershell
    PS C:\> Mount-DiskImage -StorageType ISO -ImagePath 'D:\Temp\lp\20348.1.210507-1500.fe_release_amd64fre_SERVER_LOF_PACKAGES_OEM.iso'

    Attached          : True
    BlockSize         : 0
    DevicePath        : \\.\CDROM0
    FileSize          : 6085509120
    ImagePath         : D:\Temp\lp\20348.1.210507-1500.fe_release_amd64fre_SERVER_LOF_PACKAGES_OEM.iso
    LogicalSectorSize : 2048
    Number            : 0
    Size              : 6085509120
    StorageType       : 1
    PSComputerName    :

    PS C:\> Get-Volume | Where-Object -Property 'DriveType' -EQ -Value 'CD-ROM'

    DriveLetter FriendlyName                   FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining    Size
    ----------- ------------                   -------------- --------- ------------ ----------------- -------------    ----
    G           SERVER_FOD_LP_X64FRE_MULTI_DV9 Unknown        CD-ROM    Healthy      OK                          0 B 5.67 GB
    ```

3. Obtain the cab file size of the language that you want. This is the value of **CabFileSize**.

    ```powershell
    PS C:\> (Get-Item -LiteralPath 'G:\LanguagesAndOptionalFeatures\Microsoft-Windows-Server-Language-Pack_x64_ja-jp.cab').Length
    54130307
    ```

4. Obtain the file hash of the cab file by SHA1. This is the value of **CabFileHash**.

    ```powershell
    PS C:\> (Get-FileHash -Algorithm SHA1 -LiteralPath 'G:\LanguagesAndOptionalFeatures\Microsoft-Windows-Server-Language-Pack_x64_ja-jp.cab').Hash
    298667B848087EA1377F483DC15597FD5F38A492
    ```

5. Open the language cab file by binary editor app you like. I usually using [ImHex](https://imhex.werwolv.net/) or [Stirling](https://community.chocolatey.org/packages/stirling-jp) or [Binary Editor Bz](https://gitlab.com/devill.tamachan/binaryeditorbz/). Binary Editor Bz supports English UI, Stirling is not (Japanese language only). But at this time, use [Free Hex Editor Neo](https://hhdsoftware.com/free-hex-editor) because easy to explain. (not need paid features)

    Drag and drop the cab file to Free Hex Editor Neo then the file will open.

    ![image](https://github.com/user-attachments/assets/07adf7ec-73c8-47e9-8d8d-b5daeff8b394)

6. Also open the language pack ISO file in the same way.

    ![image](https://github.com/user-attachments/assets/3d267ff6-cd25-4945-9778-32901aed8e0e)

7. Return to the cab file tab in Free Hex Editor Neo. Then select binary sequence from head (`00000000`) to appropriate length to get unique binary sequence. For example, selected from `00000000` to `0000019f` in the following screenshot.

    ![image](https://github.com/user-attachments/assets/77d030b7-a9b3-405e-970f-97e833325d0a)

8. Copy the selected binary sequence.

    ![image](https://github.com/user-attachments/assets/4986e613-ad4a-4481-9043-a5534d4eed4d)

9. Switch to the ISO file tab in Free Hex Editor Neo.

10. Open the Find window by click **Edit** - **Find** from the menu bar.

    ![image](https://github.com/user-attachments/assets/9591208b-ac51-4db0-995e-97c86281b0fb)

11. Select **Hex** and **BYTE** as **Type**. Then past copied binary sequence from the cab file tab.

    ![image](https://github.com/user-attachments/assets/07c51242-1c12-474d-909e-ce52815c8b12)

12. Click **Find** button in the Find window. Then you can obtain the offset of the cab file in the ISO file. This is the value of **OffsetToCabFileInIsoFile**.

    ![image](https://github.com/user-attachments/assets/9f2a9d90-0093-4c43-88bc-120e009e9cf8)

**Comment by jeffersonw2020** [comment]
It worked, thank you very much, I only had one question about OffsetToCabFileInIsoFile, but your tutorial explained it very well
